server:
  port: 80

spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
    probability: 1
  application:
    name: cloud-order-service

eureka:
  instance:
    instance-id: order80
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetchRegistry: true #表示是否从Eureka Server中获取注册的服务信息
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      defaultZone: http://eureka7001.com:7001/eureka