server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001   #匹配后提供服务的路由地址
        uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
        predicates:
          - Path=/payment/get/**   #断言,路径相匹配的进行路由

      - id: payment_routh2
        uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
        predicates:
          - Path=/payment/lb/**   #断言,路径相匹配的进行路由
          #- After=2021-03-22T22:15:05.073+08:00[Asia/Shanghai]
          #- Cookie=username,xfwang #并且Cookie是username=xfwang才能访问
          #- Header=X-Request-Id,\d+
          #- Cookie=password,xfwang
          - Method=GET
        filters:
          - AddRequestParameter=X-Request-Id,1024 # 再过滤器工厂会在匹配的请求头上加一堆请求头，名称为X-Request-Id 值为1024

      - id: baidu
        uri: http://news.baidu.com
        predicates:
          - Path=/guoji


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


